In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv("veriler.csv")
Y = data["cinsiyet"].values
X1 = data["kilo"].values
X2 = data["yas"].values
X3 = data["boy"].values
data

boy  kilo  yas  cinsiyet
0   130    30   10         1
1   125    36   11         1
2   135    34   10         0
3   133    30    9         0
4   129    38   12         1
5   180    90   30         1
6   190    80   25         1
7   175    90   35         1
8   177    60   22         0
9   185   105   33         1
10  165    55   27         0
11  155    50   44         0
12  160    58   39         0
13  162    59   41         0
14  167    62   55         0
15  174    70   47         1
16  193    90   23         1
17  187    80   27         1
18  183    88   28         1
19  159    40   29         0

In [15]:
X_123 = data.drop("cinsiyet",axis=1)

In [16]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X_123,Y,test_size=0.3)

In [17]:
from sklearn.ensemble import RandomForestClassifier
rf_classifier = RandomForestClassifier(n_estimators=10,criterion="entropy")  # 10 tane karar ağacı oluşsun
rf_classifier.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10)

In [18]:
y_pred = rf_classifier.predict(x_test)
y_pred

array([1, 0, 0, 1, 0, 1], dtype=int64)

In [19]:
y_test

array([1, 0, 0, 1, 0, 0], dtype=int64)

In [20]:
from sklearn.metrics import confusion_matrix
result_matrix = confusion_matrix(y_test,y_pred)
result_matrix

array([[3, 1],
       [0, 2]], dtype=int64)